name: Create Release
on:
  push:
    tags:
      - 'v*' # Trigger on tags like v1.0.0

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        

      - name: Compile LaTeX documents
        uses: xu-cheng/latex-action@v3
        with:
          root_file: "EE5213_*.tex"
          
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            EE5213_*.pdf
            docs/ASIC_Exercise1.pdf
          generate_release_notes: true
